name: grep_ui
description: wrapper on grep cli tool
publish_to: 'none'
version: 1.2.2
environment:
  sdk: ">=3.0.0 <4.0.0"
  
dependencies:
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  desktop_multi_window: ^0.2.1
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_markdown: ^0.7.7+1
  flutter_svg: ^2.2.0
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  macos_ui: ^2.2.0
  meta: ^1.16.0
  mixin_logger: ^0.1.2
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  pubspec_parse: ^1.5.0
  shared_preferences: ^2.5.3
  window_manager: ^0.4.3
  yaml: ^3.1.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/whole-word.svg
    - assets/images/app_icon_32x32@2x.png
    - pubspec.yaml
