name: grep_ui
description: wrapper on grep cli tool
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  desktop_multi_window: ^0.2.0
  event_bus: ^2.0.0
  file_picker: ^5.2.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5
  flutter_markdown: ^0.6.10+5
  flutter_svg: ^1.1.0
  hooks_riverpod: ^2.3.2
  intl: ^0.17.0
  macos_ui: ^1.12.2
  meta: ^1.7.0
  mixin_logger:
    git:
      url: https://github.com/schilken/flutter-plugins.git
      path: packages/mixin_logger
      ref: main
  path: ^1.8.1
  path_provider: ^2.0.11
  provider: ^6.0.2
  shared_preferences: ^2.0.18
  yaml: ^3.1.1
dependency_overrides:
  file: ^6.1.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
