name: grep_ui
description: wrapper on grep cli tool
publish_to: 'none'
version: 1.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"
  
dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  desktop_multi_window: ^0.2.0
  file_picker: ^5.2.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5
  flutter_markdown: ^0.6.10+5
  flutter_svg: ^2.0.4
  hooks_riverpod: ^2.3.2
  intl: ^0.17.0
  macos_ui: 
    git:
      url: https://github.com/macosui/macos_ui
      ref: dev
  meta: ^1.7.0
  mixin_logger: ^0.0.4
  path: ^1.8.1
  path_provider: ^2.0.11
  provider: ^6.0.2
  pubspec_parse: ^1.2.2
  shared_preferences: ^2.0.18
  yaml: ^3.1.1

dependency_overrides:
  file: ^6.1.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/whole-word.svg
    - assets/images/app_icon_32x32@2x.png
    - pubspec.yaml
